exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
highlighter: pygments
markdown: redcarpet 
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough", "autolink"]


# Site settings
title: 唐磊的个人博客
email: i@tanglei.me
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tanglei.name" # the base hostname & protocol for your site
twitter_username: tl3shi
github_username: tl3shi

